name: Lighthouse

on:
  push:
jobs:
  run-e2es:
    # if: github.event_name == 'deployment_status' && github.event.deployment_status.state == 'success'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@v10
        with:
          urls: |
            https://nextjs-pwa-webpush-template.vercel.app
          budgetPath: ./budget.json # test performance budgets
          uploadArtifacts: true # save results as an action artifacts
          temporaryPublicStorage: true # upload lighthouse report to the temporary storage
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.x
      - name: Lighthouse
        run: npx lighthouse-badges --url https://nextjs-pwa-webpush-template.vercel.app -o lighthouse_results
      - name: Upload Lighthouse Report
        uses: actions/upload-artifact@v4
        with:
          name: lighthouse_results
          path: lighthouse_results
